/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "and_gate.v:1" *)
module and_gate(a, b, y);
  (* src = "and_gate.v:2" *)
  input a;
  (* src = "and_gate.v:3" *)
  input b;
  (* src = "and_gate.v:4" *)
  output y;
  assign y = b & a;
endmodule
