/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "mux_2to1.v:1" *)
module mux_2to1(a, b, sel, y);
  (* src = "mux_2to1.v:2" *)
  input a;
  (* src = "mux_2to1.v:3" *)
  input b;
  (* src = "mux_2to1.v:4" *)
  input sel;
  (* src = "mux_2to1.v:5" *)
  output y;
  assign y = sel ? b : a;
endmodule
